name: Build Token Typings
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
        name: Install modules
      - run: touch tokens.ts
        name: Create tokens file
      - run: npm run build-tokens
        name: Fill tokens from JSON
